// This file is auto-generated by FlutterFire CLI.
// Run: flutterfire configure
// Then replace this file with the generated one.
//
// TO SET UP FIREBASE:
// 1. Go to https://console.firebase.google.com
// 2. Create a new project named "expense-calculator"
// 3. Add an Android app with package name: com.group19.expense_calculator
// 4. Add an iOS app if needed
// 5. Run: dart pub global activate flutterfire_cli
// 6. Run: flutterfire configure
// 7. This file will be auto-generated and replace this placeholder

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ REPLACE THESE WITH YOUR ACTUAL FIREBASE CONFIG VALUES
  // Get these from: Firebase Console > Project Settings > Your Apps

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDweWkOIjarmO6ENFHbH3gmlZtjxEedTbI',
    appId: '1:357318238954:web:099ea145a42c6537d42d93',
    messagingSenderId: '357318238954',
    projectId: 'expense-calculator-71ad2',
    authDomain: 'expense-calculator-71ad2.firebaseapp.com',
    storageBucket: 'expense-calculator-71ad2.firebasestorage.app',
    measurementId: 'G-60RL8SY06P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjE1TcItUv99bRtN1IkguI6h2QsdVq6Fs',
    appId: '1:357318238954:android:42a47446dd3288ddd42d93',
    messagingSenderId: '357318238954',
    projectId: 'expense-calculator-71ad2',
    storageBucket: 'expense-calculator-71ad2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.group19.expenseCalculator',
  );
}
